package chatclientv5.chat;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import chatclientv5.login.WarmingDialog;
import chatclientv5.util.UiUtil;

/**
 *
 * @author yusij
 */


    public class AddDialog extends javax.swing.JDialog {

        /**
         * Creates new form AddDialog
         *
         * @param parent
         * @param modal
         * @param b
         */
        boolean b;
        MainFrame mf;

        public AddDialog(java.awt.Frame parent, boolean modal, boolean b) {
            super(parent, modal);
            this.b = b;
            mf = (MainFrame) parent;
            initComponents();
            myinit(b);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            idnum = new javax.swing.JTextField();
            addButton = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

            jLabel1.setText("好友账号：");

            addButton.setText("添加");
            addButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    addButtonActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(idnum, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addButton)
                                    .addContainerGap())
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1)
                                            .addComponent(idnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(addButton)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

        private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
            String result = null;
            String name = idnum.getText();
            if (name.length() < 2) {
                new WarmingDialog(mf, true, false);
                return;
            }
            if (b) {
                result = mf.sander.write("AddFriend\n" + name);
            } else {
                result = mf.sander.write("AddGroup\n" + name);
            }
            if (result.equalsIgnoreCase("ok")) {
                new WarmingDialog(mf, true, true);
                if (b) {
                    mf.freshFriends();
                } else {
                    mf.freshGroups();
                }
            }else{
                new WarmingDialog(mf, true, false);
            }
        }//GEN-LAST:event_addButtonActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton addButton;
        private javax.swing.JTextField idnum;
        private javax.swing.JLabel jLabel1;
        // End of variables declaration//GEN-END:variables

        private void myinit(boolean b) {
            UiUtil.setCenter(this);
            this.setResizable(false);
            this.setAlwaysOnTop(true);
            if (b) {
                this.setTitle("Add Friend");
            } else {
                this.setTitle("Add Group");
                this.jLabel1.setText("群组名称：");
            }
            this.setVisible(true);
        }
    }
